### ISSUE TITLE
backend with @tensorflow/tfjs-node ?

### ISSUE THREAD

**Issue by AZOPCORP** [infinitered/nsfwjs#25] opened 2019-02-24 22:10 UTC
could it be possible to port the lib for backend use via tfjs-node and node canvas?

**Comment by GantMan** [comment] 2019-02-26 04:26
Hey @AZOPCORP - so I've recently solved how to do this!  (I think)

I made a test, and for that to work it had to run 100% in node.  This test runs a classification on the logo without accessing a browser.
https://github.com/infinitered/nsfwjs/blob/master/__tests__/regressionCheck.ts

I hope the setup code in this test works for you.   I'm sure it could be better wrapped in the actual lib though.   If you do use this lib on a backend, please contribute back any improvements 👍

**Comment by AZOPCORP** [comment] 2019-02-27 15:15
Thanx for your answer, 

everything works fine using @tensorflow/tfjs but i get this error using @tensorflow/tfsj-node instead (would like to use native C++ bindings or cuda  to speed up prediction)

```
(node:50868) UnhandledPromiseRejectionWarning: Error: Found more than one (2) load handlers for URL 'https://s3.amazonaws.com/ir_public/nsfwjs/model.json'
    at new ValueError (\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\errors.js:36:28)
    at Object.<anonymous> (\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\models.js:109:27)
    at step (\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\models.js:42:23)
    at Object.next (\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\models.js:23:53)
    at\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\models.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\models.js:13:12)
    at Object.loadModelInternal (\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\models.js:97:12)
    at Object.loadLayersModel (\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\exports.js:27:21)
    at NSFWJS.<anonymous> (\nsfwjs\dist\index.js:77:39)
(node:50868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:50868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

seems that the model is not compatble with tfjs-node 


also the load function only accept xhr call, would be nice to load model from local file system

```
(node:50868) UnhandledPromiseRejectionWarning: Error: Found more than one (2) load handlers for URL 'https://s3.amazonaws.com/ir_public/nsfwjs/model.json'
    at new ValueError (\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\errors.js:36:28)
    at Object.<anonymous> (\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\models.js:109:27)
    at step (\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\models.js:42:23)
    at Object.next (\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\models.js:23:53)
    at\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\models.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\models.js:13:12)
    at Object.loadModelInternal (\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\models.js:97:12)
    at Object.loadLayersModel (\nsfwjs\node_modules\@tensorflow\tfjs-layers\dist\exports.js:27:21)
    at NSFWJS.<anonymous> (\nsfwjs\dist\index.js:77:39)
(node:50868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:50868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
here is my test code , adapted from yours:

```js
const tf =require('@tensorflow/tfjs')
const load=require('./dist/index').load

const fs = require('fs');
const jpeg = require('jpeg-js');


// Fix for JEST
const globalAny = global
globalAny.fetch = require('node-fetch')
const timeoutMS = 10000
const NUMBER_OF_CHANNELS = 3


const readImage = (path) => {
  const buf = fs.readFileSync(path)
  const pixels = jpeg.decode(buf, true)
  return pixels
}


const imageByteArray = (image, numChannels) => {
  const pixels = image.data
  const numPixels = image.width * image.height;
  const values = new Int32Array(numPixels * numChannels);

  for (let i = 0; i < numPixels; i++) {
    for (let channel = 0; channel < numChannels; ++channel) {
      values[i * numChannels + channel] = pixels[i * 4 + channel];
    }
  }

  return values
}


const imageToInput = (image, numChannels) => {
  const values = imageByteArray(image, numChannels)
  const outShape = [image.height, image.width, numChannels] ;
  const input = tf.tensor3d(values, outShape, 'int32');

  return input
}

    (async()=>{
        const model = await load('./example/public/model')
  const logo = readImage(`./_art/nsfwjs_logo.jpg`)
  const input = imageToInput(logo, NUMBER_OF_CHANNELS)
  const predictions = await model.classify(input)
  expect(predictions).toMatchSnapshot()
    })()
  

```

Thanx for your awesome job !

**Comment by AZOPCORP** [comment] 2019-02-27 17:02
Thanx for your awesome job!

Below a working eg with tfjs-node based on your test:

```js
const tf =require('@tensorflow/tfjs-node')
const load=require('./dist/index').load

const fs = require('fs');
const jpeg = require('jpeg-js');


// Fix for JEST
const globalAny = global
globalAny.fetch = require('node-fetch')
const timeoutMS = 10000
const NUMBER_OF_CHANNELS = 3


const readImage = (path) => {
  const buf = fs.readFileSync(path)
  const pixels = jpeg.decode(buf, true)
  return pixels
}


const imageByteArray = (image, numChannels) => {
  const pixels = image.data
  const numPixels = image.width * image.height;
  const values = new Int32Array(numPixels * numChannels);

  for (let i = 0; i < numPixels; i++) {
    for (let channel = 0; channel < numChannels; ++channel) {
      values[i * numChannels + channel] = pixels[i * 4 + channel];
    }
  }

  return values
}


const imageToInput = (image, numChannels) => {
  const values = imageByteArray(image, numChannels)
  const outShape = [image.height, image.width, numChannels] ;
  const input = tf.tensor3d(values, outShape, 'int32');

  return input
}


    (async()=>{
        const model = await load('file://./model/')//moved model at root of folder
  const logo = readImage(`./_art/nsfwjs_logo.jpg`)
  const input = imageToInput(logo, NUMBER_OF_CHANNELS)
  console.time('predict')
  const predictions = await model.classify(input)
  console.timeEnd('predict')
 console.log(predictions)
    })()
```

**Comment by GantMan** [comment] 2019-02-28 01:30
very cool! 

Maybe we should put an example in the demo folder?

**Comment by AZOPCORP** [comment] 2019-02-28 08:59
Something like  a way to pass some options to configure lib using tfjs-node and tfjs-node-gpu would be much apreciated I think.  BTW i will make a backend demo as soon as i have the time.

**Comment by scratcher28** [comment] 2019-03-20 13:22
**AZOPCORP**, I am getting this Error: Request for file://.model/model.json failed due to error: TypeError: Only HTTP(S) protocols are supported.

**Comment by GantMan** [comment] 2019-04-04 23:57
Closing because question moved to https://github.com/infinitered/nsfwjs/wiki/FAQ:-NSFW-JS

**Closed by GantMan** 2019-04-04 23:57 UTC
Labels: enhancement, question

**Comment by mycaule** [comment] 2019-12-18 18:23
For information this guy code works
https://github.com/mishazawa/nums

When you do `npm install nsfwjs` and use the following it doesn't work immediately.

```
const nsfwjs = require('nsfw/dist')
```
He basically forked the code to [`lib/nsfwjs/index.js`](https://github.com/mishazawa/nums/blob/master/lib/nsfwjs/index.js) and made minor changes to make it runnable. 

It would be nice and not too much work to have this published to npmjs.org.

Similarly you can use [`@tensorflow-models/toxicity`](https://www.npmjs.com/package/@tensorflow-models/toxicity) pretty easily on server side using just 

```
const toxicity = require('@tensorflow-models/toxicity')

const sentences = ['I love C++']

toxicity.load(0.9).then(model =>
  model.classify(sentences).then(predictions =>
    console.log(JSON.stringify(predictions))
)
```

**Comment by GantMan** [comment] 2019-12-20 17:01
I wish he had contributed back with a Pull Request.   @mycaule - would you be willing to take a shot?

If not, this is something I could get around to at some point.

**Comment by mycaule** [comment] 2019-12-21 00:19
Ok I will try to do this week end
